services:
  tasandjet.api:
    image: ${DOCKER_REGISTRY-}tasandjetapi
    build:
      context: .
      dockerfile: TasAndJet.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tasandjet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  postgres-data:
